### PR TITLE
MIM-104: add computed field for has elevator

### PR DESCRIPTION
**Pull request by lalmqvist**

### CODE REVIEW

**Review by henrikhenrikpersson — APPROVED** [review]
🛗

**Review by johanneskarlsson — COMMENTED** [review]
Couldn't we just changed the value in core instead? Since `has_elevator` is a fields.Char we can just pass in ja/nej?

**Comment by lalmqvist** [comment]
> Couldn't we just changed the value in core instead? Since `has_elevator` is a fields.Char we can just pass in ja/nej?

Ah, didn't even think of that. Can't think of any reason why not.

**Comment by lalmqvist** [comment]
Will make changes in the core API instead.

**Pull request closed without merging**
